'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AllergyType
    Public Property AllergyTypeCd As String
    Public Property AllergyTypeDesc As String

    Public Overridable Property PatientAllergies As ICollection(Of PatientAllergy) = New HashSet(Of PatientAllergy)

End Class
