'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Diagnosi
    Public Property DiagCd As String
    Public Property DiagDesc As String

    Public Overridable Property PatientDiagnosis As ICollection(Of PatientDiagnosi) = New HashSet(Of PatientDiagnosi)

End Class
