'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Disability
    Public Property DisabilityCd As String
    Public Property DisabilityDesc As String

    Public Overridable Property PatientDisabilities As ICollection(Of PatientDisability) = New HashSet(Of PatientDisability)

End Class
