'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailMessage
    Public Property EmailMessageID As Integer
    Public Property EmailMessageTypeCd As String
    Public Property EmailMessageSubject As String
    Public Property EmailMessageBody As String

End Class
