'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Hospital
    Public Property HospitalID As String
    Public Property HospitalName As String
    Public Property HospitalSpecialityCd As String
    Public Property HandicapAccess As Nullable(Of Boolean)
    Public Property ICURoom As Nullable(Of Boolean)
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property PinCode As String
    Public Property State As String
    Public Property MainPhone As String
    Public Property OtherPhone As String
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Hospital1 As Hospital
    Public Overridable Property Hospital2 As Hospital

End Class
