'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HospitalSpeciality
    Public Property HospitalSpecialityCd As String
    Public Property HospitalSpecialityDesc As String

    Public Overridable Property OtherHospitals As ICollection(Of OtherHospital) = New HashSet(Of OtherHospital)

End Class
