'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MedicationDetail
    Public Property MedicationDetailID As Integer
    Public Property MedicationID As Integer
    Public Property MedicationDesc As String
    Public Property NoOfTimesDay As Nullable(Of Integer)
    Public Property NoOfDays As Nullable(Of Integer)
    Public Property Dosage As String
    Public Property MedicationSubCatCd As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Medication As Medication

End Class
