'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Occupation
    Public Property OccupationCd As String
    Public Property OccupationDesc As String

    Public Overridable Property Patients As ICollection(Of Patient) = New HashSet(Of Patient)

End Class
