'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OtherHospital
    Public Property HospitalID As Integer
    Public Property HospitalName As String
    Public Property HospitalSpecialityCd As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property State As String
    Public Property PinCode As String
    Public Property Country As String
    Public Property BusinessPhone As String
    Public Property FaxNumber As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property HospitalSpeciality As HospitalSpeciality
    Public Overridable Property OtherHospitals1 As OtherHospital
    Public Overridable Property OtherHospital1 As OtherHospital

End Class
