'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientAllergy
    Public Property PatAllergyID As Integer
    Public Property PatientID As Integer
    Public Property AllergyCd As String
    Public Property AllergyTypeCd As String
    Public Property IdentificationDate As Nullable(Of Date)
    Public Property AllergySeverityCd As String
    Public Property AllergyReaction As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredBy As String
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Allergy As Allergy
    Public Overridable Property AllergySeverity As AllergySeverity
    Public Overridable Property AllergyType As AllergyType

End Class
