'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientImmunization
    Public Property PatImmunizationID As Integer
    Public Property PatientID As Integer
    Public Property ImmunizationCd As String
    Public Property ImmunizationDate As Date
    Public Property VisitID As Nullable(Of Integer)
    Public Property PhysicianID As Integer
    Public Property ImmunizationGivenByID As Nullable(Of Integer)
    Public Property ImmunizationNotes As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Immunization As Immunization

End Class
