'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientVisionCare
    Public Property PatVisionCareID As Integer
    Public Property PatientID As Integer
    Public Property VisionCareCd As String
    Public Property VisionCareDate As Date
    Public Property VisionClinicName As String
    Public Property VisionCareProviderName As String
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property StaffID As Nullable(Of Integer)
    Public Property VisitID As Nullable(Of Integer)
    Public Property Notes As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Physician As Physician
    Public Overridable Property Staff As Staff
    Public Overridable Property VisionCare As VisionCare

End Class
