'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientInsurance
    Public Property PatInsuranceID As Integer
    Public Property PatientID As Integer
    Public Property InsuranceCompanyID As Integer
    Public Property InsuranceNumber As String
    Public Property PolicyNumber As String
    Public Property FromDate As Nullable(Of Date)
    Public Property CoverageAmount As Nullable(Of Decimal)
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

End Class
