'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedicalReferal
    Public Property PatMedicalReferalID As Integer
    Public Property PatientID As Integer
    Public Property PhysicianID As Integer
    Public Property ReferToPhysicianID As Integer
    Public Property ReferDate As Date
    Public Property VisitID As Nullable(Of Integer)
    Public Property DiagCd As String
    Public Property Notes As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Patient As Patient
    Public Overridable Property Physician As Physician
    Public Overridable Property Physician1 As Physician

End Class
