'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Patient
    Public Property PatientID As Integer
    Public Property LastName As String
    Public Property FirstName As String
    Public Property MiddleInitial As String
    Public Property DOB As Date
    Public Property GenderCd As String
    Public Property MaritialStatusCd As String
    Public Property ReligionCd As String
    Public Property RaceCd As String
    Public Property OccupationCd As String
    Public Property Employer As String
    Public Property PassportNumber As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Date
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property Gender As Gender
    Public Overridable Property MaritialStatu As MaritialStatu
    Public Overridable Property Occupation As Occupation
    Public Overridable Property Patient1 As Patient
    Public Overridable Property Patient2 As Patient
    Public Overridable Property Race As Race
    Public Overridable Property Religion As Religion
    Public Overridable Property PatientDemographics As ICollection(Of PatientDemographic) = New HashSet(Of PatientDemographic)
    Public Overridable Property PatientDisabilities As ICollection(Of PatientDisability) = New HashSet(Of PatientDisability)
    Public Overridable Property PatientHabits As ICollection(Of PatientHabit) = New HashSet(Of PatientHabit)
    Public Overridable Property PatientMedicalProcedures As ICollection(Of PatientMedicalProcedure) = New HashSet(Of PatientMedicalProcedure)
    Public Overridable Property PatientMedicalReferals As ICollection(Of PatientMedicalReferal) = New HashSet(Of PatientMedicalReferal)
    Public Overridable Property PatientMessages As ICollection(Of PatientMessage) = New HashSet(Of PatientMessage)
    Public Overridable Property PhysicianMessages As ICollection(Of PhysicianMessage) = New HashSet(Of PhysicianMessage)

End Class
