'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientDemographic
    Public Property PatDemographicID As Integer
    Public Property PatientID As Integer
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property District As String
    Public Property State As String
    Public Property PinCode As String
    Public Property Country As String
    Public Property HomePhone As String
    Public Property BusinessPhone As String
    Public Property EmailAddress As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Date
    Public Property EnteredBy As String
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As String
    Public Property FaxNumber As String

    Public Overridable Property Patient As Patient

End Class
