'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedication
    Public Property PatMedicationID As Integer
    Public Property PatientID As Integer
    Public Property MedicationDate As Date
    Public Property VisitID As Nullable(Of Integer)
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property SpecialNotes As String
    Public Property Active As Boolean
    Public Property DateEntered As Date
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property PatientMedication1 As PatientMedication
    Public Overridable Property PatientMedication2 As PatientMedication
    Public Overridable Property PatientMedicationDetails As ICollection(Of PatientMedicationDetail) = New HashSet(Of PatientMedicationDetail)

End Class
