'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedicalProcedure
    Public Property PatProcedureID As Integer
    Public Property PatientID As Integer
    Public Property ProcedureCd As String
    Public Property ProcedureDate As Date
    Public Property PastProcedure As Boolean
    Public Property VisitID As Nullable(Of Integer)
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property ConsultingPhysicianID As Nullable(Of Integer)
    Public Property ProcedurePractitionerTypeCd As String
    Public Property ProcedureStaffID As Nullable(Of Integer)
    Public Property Notes As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Date
    Public Property EnteredBy As String
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As String

    Public Overridable Property MedicalProcedure As MedicalProcedure
    Public Overridable Property Patient As Patient
    Public Overridable Property PatientMedicalProcedure1 As PatientMedicalProcedure
    Public Overridable Property PatientMedicalProcedure2 As PatientMedicalProcedure

End Class
