'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedicationDetail
    Public Property PatMedDetailID As Integer
    Public Property PatMedicationID As Integer
    Public Property MedicationDesc As String
    Public Property NoOfTimesDay As Nullable(Of Integer)
    Public Property NoOfDays As Nullable(Of Integer)
    Public Property Dosage As String
    Public Property SpecialNote As String
    Public Property Active As Boolean
    Public Property DateEntered As Date
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property PatientMedication As PatientMedication

End Class
