'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientVitalSign
    Public Property PatVitalSignID As Integer
    Public Property PatientID As Integer
    Public Property VitalSignDate As Date
    Public Property VisitID As Nullable(Of Integer)
    Public Property Height As Nullable(Of Decimal)
    Public Property Weight As Nullable(Of Decimal)
    Public Property Temperature As Nullable(Of Decimal)
    Public Property Pulse As Nullable(Of Decimal)
    Public Property BloodPressure As Nullable(Of Decimal)
    Public Property RepositaryRate As Nullable(Of Decimal)
    Public Property PainScale As Nullable(Of Integer)
    Public Property UrinaryContinence As String
    Public Property EmotionalDistress As String
    Public Property Spirometry As String
    Public Property Glucose As String
    Public Property FunctionalStatus As String
    Public Property OxygenSaturationLevel As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

End Class
