'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientMedicalReferalRequest
    Public Property PatMedReferalRequestID As Integer
    Public Property ReqFromPatientID As Integer
    Public Property ReqForPhysicianID As Integer
    Public Property MedReferalReqDate As Date
    Public Property ReferedPhysicianID As Integer
    Public Property WorkFlowStatus As String
    Public Property Active As Boolean
    Public Property DateEntered As Date
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

End Class
