'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PatientAssociatedParty
    Public Property PatAssocPartyID As Integer
    Public Property PatientID As Integer
    Public Property AssociatedPartyLastName As String
    Public Property AssociatedPartyFirstName As String
    Public Property RelationshipCd As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property State As String
    Public Property Country As String
    Public Property HomePhone As String
    Public Property BusinessPhone As String
    Public Property EmailAddress As String
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)
    Public Property PinCode As String

End Class
