'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Physician
    Public Property PhysicianID As Integer
    Public Property PhysicianLastName As String
    Public Property PhysicianFirstName As String
    Public Property MiddleInitial As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property State As String
    Public Property PinCode As String
    Public Property Country As String
    Public Property HomePhone As String
    Public Property BusinessPhone As String
    Public Property EmailAddress As String
    Public Property FaxNumber As String
    Public Property ProviderSpecialityCd As String
    Public Property PhysicianTypeCd As String
    Public Property GenderCd As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

    Public Overridable Property PatientMedicalReferals As ICollection(Of PatientMedicalReferal) = New HashSet(Of PatientMedicalReferal)
    Public Overridable Property PatientMedicalReferals1 As ICollection(Of PatientMedicalReferal) = New HashSet(Of PatientMedicalReferal)
    Public Overridable Property PatientMessages As ICollection(Of PatientMessage) = New HashSet(Of PatientMessage)
    Public Overridable Property PatientVisionCares As ICollection(Of PatientVisionCare) = New HashSet(Of PatientVisionCare)
    Public Overridable Property PhysicianSpeciality As PhysicianSpeciality
    Public Overridable Property PhysicianSpeciality1 As PhysicianSpeciality
    Public Overridable Property PhysicianMessages As ICollection(Of PhysicianMessage) = New HashSet(Of PhysicianMessage)

End Class
