'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PhysicianLoginHistory
    Public Property PhysicianLoginHistoryID As Nullable(Of Integer)
    Public Property PhysicianID As Integer
    Public Property UserName As String
    Public Property LoginDate As Nullable(Of Date)

End Class
