'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Staff
    Public Property StaffID As Integer
    Public Property LastName As String
    Public Property FirstName As String
    Public Property DOB As String
    Public Property JoinDate As Nullable(Of Date)
    Public Property StaffCatCd As String
    Public Property Title As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property State As String
    Public Property PinCode As String
    Public Property Country As String
    Public Property HomePhone As String
    Public Property OtherPhone As String
    Public Property EmailAddress As String
    Public Property GenderCd As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As String
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As String

    Public Overridable Property Gender As Gender
    Public Overridable Property PatientVisionCares As ICollection(Of PatientVisionCare) = New HashSet(Of PatientVisionCare)
    Public Overridable Property StaffCategory As StaffCategory

End Class
