'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VisitRecordParameter
    Public Property ParameterCd As String
    Public Property ParameterDesc As String

    Public Overridable Property PatientInpatientVisitRecordParameters As ICollection(Of PatientInpatientVisitRecordParameter) = New HashSet(Of PatientInpatientVisitRecordParameter)

End Class
