'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PhysicianSchedule
    Public Property PhysicianScheduleID As Integer
    Public Property PhysicianID As Integer
    Public Property LocationCd As String
    Public Property ScheduleYear As Integer
    Public Property WeekNum As Nullable(Of Integer)
    Public Property ScheduleDate As Nullable(Of Date)
    Public Property Day1FromTime As String
    Public Property Day1ToTime As String
    Public Property Day2FromTime As String
    Public Property Day2ToTime As String
    Public Property Day3FromTime As String
    Public Property Day3ToTime As String
    Public Property Day4FromTime As String
    Public Property Day4ToTime As String
    Public Property Day5FromTime As String
    Public Property Day5ToTime As String
    Public Property Day6FromTime As String
    Public Property Day6ToTime As String
    Public Property Day7FromTime As String
    Public Property Day7ToTime As String
    Public Property LocationName As String
    Public Property PhysicianName As String
    Public Property WkStartDate As Date
    Public Property WkEndDate As Date

End Class
