'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientRadiology
    Public Property PatRadiologyID As Integer
    Public Property PatientID As Integer
    Public Property PatientName As String
    Public Property VisitID As Nullable(Of Integer)
    Public Property RadiologyReason As String
    Public Property RadiologyCd As String
    Public Property RadiologyDesc As String
    Public Property RadiologyDate As Date
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property PhysicianName As String
    Public Property RadiologyResult As String
    Public Property Notes As String
    Public Property RadiologyImage As Byte()
    Public Property RadiologyLabName As String
    Public Property RadiologyLabEmailAddress As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedByUserID As Nullable(Of Integer)

End Class
