'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PhysicianMessage
    Public Property PhysMsgID As Integer
    Public Property MsgForPhysicianID As Integer
    Public Property MsgFromPatientID As Integer
    Public Property MsgDate As Date
    Public Property MsgSubject As String
    Public Property MsgBody As String
    Public Property MsgStatus As String
    Public Property Active As Nullable(Of Boolean)
    Public Property PatientName As String
    Public Property PhysicianName As String

End Class
