'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientPhysiotherapy
    Public Property PatPhysiotherapyID As Integer
    Public Property PatientID As Integer
    Public Property VisitID As Nullable(Of Integer)
    Public Property PhysiotherapyReason As String
    Public Property PhysiotherapyCd As String
    Public Property PhysiotherapyDate As Date
    Public Property PhysiotherapistName As String
    Public Property PhysioTherapyDesc As String
    Public Property PatientName As String
    Public Property Notes As String
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)

End Class
