'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientInsuranceClaim
    Public Property PatientID As Integer
    Public Property LastName As String
    Public Property FirstName As String
    Public Property DiagCd As String
    Public Property DiagDate As Date
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property InsuranceNumber As String
    Public Property PolicyNumber As String
    Public Property DiagDesc As String
    Public Property CompanyName As String

End Class
