'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientAccident
    Public Property PatAccidentID As Integer
    Public Property PatientID As Integer
    Public Property AccidentDate As Date
    Public Property AccidentTime As String
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property Notes As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property PatientName As String
    Public Property PhysicianName As String
    Public Property StaffName As String

End Class
