'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_Physician
    Public Property PhysicianID As Integer
    Public Property PhysicianLastName As String
    Public Property PhysicianFirstName As String
    Public Property PhysicianName As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property PinCode As String
    Public Property Country As String
    Public Property HomePhone As String
    Public Property BusinessPhone As String
    Public Property EmailAddress As String
    Public Property PhysicianSpecialityDesc As String
    Public Property PhysicianTypeDesc As String
    Public Property GenderDesc As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property State As String
    Public Property StateDesc As String
    Public Property CountryDesc As String
    Public Property ProviderSpecialityCd As String
    Public Property PhysicianTypeCd As String
    Public Property GenderCd As String
    Public Property UserName As String
    Public Property Password As String
    Public Property FaxNumber As String

End Class
