'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientMedicalReferal
    Public Property PatientID As Integer
    Public Property PhysicianID As Integer
    Public Property ReferDate As Date
    Public Property DiagCd As String
    Public Property Notes As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Nullable(Of Date)
    Public Property EnteredByUserID As Nullable(Of Integer)
    Public Property PatMedicalReferalID As Integer
    Public Property ReferToPhysicianID As Integer
    Public Property ReferedByPhysicianName As String
    Public Property ReferToPhysicianName As String
    Public Property DiagDesc As String
    Public Property PatientName As String
    Public Property PhysicianEmailAddress As String
    Public Property VisitID As Nullable(Of Integer)

End Class
