'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientDetail
    Public Property PatientID As Integer
    Public Property PatientName As String
    Public Property MiddleInitial As String
    Public Property DOB As Date
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property StateDesc As String
    Public Property CountryDesc As String
    Public Property GenderDesc As String
    Public Property HomePhone As String
    Public Property BusinessPhone As String
    Public Property PatientEmailAddress As String
    Public Property GuarantorName As String
    Public Property AssociatedPartyName As String
    Public Property InsuranceName As String
    Public Property age As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Date
    Public Property LastName As String
    Public Property FirstName As String
    Public Property GenderCd As String
    Public Property MaritialStatusCd As String
    Public Property ReligionCd As String
    Public Property RaceCd As String
    Public Property OccupationCd As String
    Public Property Employer As String
    Public Property PassportNumber As String
    Public Property PinCode As String

End Class
