'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientMedicalHistory
    Public Property PatMedicalHistoryID As Integer
    Public Property PatientID As Integer
    Public Property MedicalHistoryCd As String
    Public Property MedicalHistoryDesc As String
    Public Property PatientName As String
    Public Property FamilyHistory As Nullable(Of Boolean)
    Public Property Active As Nullable(Of Boolean)

End Class
