'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientInpatientVisit
    Public Property VisitID As Integer
    Public Property PatientID As Integer
    Public Property PatientName As String
    Public Property VisitStartDateTime As Date
    Public Property LocationCd As String
    Public Property LocationName As String
    Public Property AdmissionTypeCd As String
    Public Property AdmissionTypeDesc As String
    Public Property AdmitDate As Nullable(Of Date)
    Public Property HospitalRoomID As Nullable(Of Integer)
    Public Property RoomCd As String
    Public Property BedNumber As Nullable(Of Integer)
    Public Property TransferDate As Nullable(Of Date)
    Public Property TransferToRoomID As Nullable(Of Integer)
    Public Property TransferToBedNumber As Nullable(Of Integer)
    Public Property AmbulatoryStatusCd As String
    Public Property AmbulatoryStatusDesc As String
    Public Property PhysicianID As Integer
    Public Property PhysicianName As String
    Public Property DischargeDate As Nullable(Of Date)
    Public Property DeathInHospital As Nullable(Of Boolean)
    Public Property DeathDate As Nullable(Of Date)
    Public Property DischargeNotes As String
    Public Property ReferringPhysicianID As Nullable(Of Integer)
    Public Property ConsultingPhysicianID As Nullable(Of Integer)
    Public Property VisitEndDateTime As Nullable(Of Date)
    Public Property VisitType As String
    Public Property Active As Nullable(Of Boolean)

End Class
