'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_PatientMedicalProcedure
    Public Property PatProcedureID As Integer
    Public Property PatientID As Integer
    Public Property ProcedureCd As String
    Public Property ProcedureDate As Date
    Public Property VisitID As Nullable(Of Integer)
    Public Property PhysicianID As Nullable(Of Integer)
    Public Property ProcedurePractitionerTypeCd As String
    Public Property Active As Nullable(Of Boolean)
    Public Property DateEntered As Date
    Public Property EnteredBy As String
    Public Property ProcedureDesc As String
    Public Property ProcedurePractitionerTypeDesc As String
    Public Property PhysicianName As String
    Public Property PatientName As String
    Public Property ConsultingPhysicianID As Nullable(Of Integer)
    Public Property ProcedureStaffID As Nullable(Of Integer)
    Public Property Notes As String
    Public Property PastProcedure As Boolean

End Class
