'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_StaffList
    Public Property StaffID As Integer
    Public Property StaffName As String
    Public Property DOB As String
    Public Property JoinDate As Nullable(Of Date)
    Public Property StaffCatCd As String
    Public Property StaffCatDesc As String
    Public Property Title As String
    Public Property HomePhone As String
    Public Property OtherPhone As String
    Public Property EmailAddress As String
    Public Property DateEntered As Nullable(Of Date)
    Public Property LastName As String
    Public Property FirstName As String
    Public Property State As String
    Public Property Country As String
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property PinCode As String
    Public Property GenderCd As String
    Public Property StateDesc As String
    Public Property CountryDesc As String
    Public Property Active As Nullable(Of Boolean)
    Public Property UserName As String
    Public Property Password As String

End Class
