'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class YearCalendar
    Public Property Year As Integer
    Public Property WeekNum As Integer
    Public Property WkStartDate As Date
    Public Property WkEndDate As Date

End Class
