'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class InsuranceEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=InsuranceEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Diagnosis() As DbSet(Of Diagnosi)
    Public Overridable Property Genders() As DbSet(Of Gender)
    Public Overridable Property MaritialStatus() As DbSet(Of MaritialStatu)
    Public Overridable Property MedicalProcedures() As DbSet(Of MedicalProcedure)
    Public Overridable Property Occupations() As DbSet(Of Occupation)
    Public Overridable Property Patients() As DbSet(Of Patient)
    Public Overridable Property Physicians() As DbSet(Of Physician)
    Public Overridable Property PhysicianSpecialities() As DbSet(Of PhysicianSpeciality)
    Public Overridable Property PolicyTypes() As DbSet(Of PolicyType)

End Class
