'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PhysicianSpeciality
    Public Property PhysicianSpecialityCd As String
    Public Property PhysicianSpecialityDesc As String
    Public Property PhysicianSpecialityDetailDesc As String

    Public Overridable Property Physicians As ICollection(Of Physician) = New HashSet(Of Physician)
    Public Overridable Property Physicians1 As ICollection(Of Physician) = New HashSet(Of Physician)

End Class
