'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PolicyType
    Public Property PolicyTypeCd As String
    Public Property PolicyTypeDesc As String
    Public Property CoverPrescription As Nullable(Of Boolean)
    Public Property CoverProcedure As Nullable(Of Boolean)
    Public Property CoverVisitCopay As Nullable(Of Boolean)
    Public Property CoverVision As Nullable(Of Boolean)
    Public Property CoverDental As Nullable(Of Boolean)
    Public Property MinCoverageAmount As Nullable(Of Decimal)
    Public Property MaxCoverageAmount As Nullable(Of Decimal)

End Class
