'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace InsuranceClaimServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InsuranceClaim", [Namespace]:="http://schemas.datacontract.org/2004/07/InsuranceClaimService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InsuranceClaim
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AppointmentDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChargeField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DiagnosisCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InsuranceNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MedicalProcedureCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PolicyNumberField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AppointmentDate() As Date
            Get
                Return Me.AppointmentDateField
            End Get
            Set
                If (Me.AppointmentDateField.Equals(value) <> true) Then
                    Me.AppointmentDateField = value
                    Me.RaisePropertyChanged("AppointmentDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Charge() As Decimal
            Get
                Return Me.ChargeField
            End Get
            Set
                If (Me.ChargeField.Equals(value) <> true) Then
                    Me.ChargeField = value
                    Me.RaisePropertyChanged("Charge")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DiagnosisCode() As String
            Get
                Return Me.DiagnosisCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DiagnosisCodeField, value) <> true) Then
                    Me.DiagnosisCodeField = value
                    Me.RaisePropertyChanged("DiagnosisCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InsuranceNumber() As String
            Get
                Return Me.InsuranceNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InsuranceNumberField, value) <> true) Then
                    Me.InsuranceNumberField = value
                    Me.RaisePropertyChanged("InsuranceNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MedicalProcedureCode() As String
            Get
                Return Me.MedicalProcedureCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MedicalProcedureCodeField, value) <> true) Then
                    Me.MedicalProcedureCodeField = value
                    Me.RaisePropertyChanged("MedicalProcedureCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PolicyNumber() As String
            Get
                Return Me.PolicyNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PolicyNumberField, value) <> true) Then
                    Me.PolicyNumberField = value
                    Me.RaisePropertyChanged("PolicyNumber")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="InsuranceClaimServiceReference.IInsuranceClaimService")>  _
    Public Interface IInsuranceClaimService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInsuranceClaimService/GetInsuranceClaim", ReplyAction:="http://tempuri.org/IInsuranceClaimService/GetInsuranceClaimResponse")>  _
        Function GetInsuranceClaim(ByVal subscriberId As String) As InsuranceClaimServiceReference.InsuranceClaim()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInsuranceClaimService/GetInsuranceClaim", ReplyAction:="http://tempuri.org/IInsuranceClaimService/GetInsuranceClaimResponse")>  _
        Function GetInsuranceClaimAsync(ByVal subscriberId As String) As System.Threading.Tasks.Task(Of InsuranceClaimServiceReference.InsuranceClaim())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInsuranceClaimService/ClaimInsurance", ReplyAction:="http://tempuri.org/IInsuranceClaimService/ClaimInsuranceResponse")>  _
        Function ClaimInsurance(ByVal insuranceClaims() As InsuranceClaimServiceReference.InsuranceClaim) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInsuranceClaimService/ClaimInsurance", ReplyAction:="http://tempuri.org/IInsuranceClaimService/ClaimInsuranceResponse")>  _
        Function ClaimInsuranceAsync(ByVal insuranceClaims() As InsuranceClaimServiceReference.InsuranceClaim) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IInsuranceClaimServiceChannel
        Inherits InsuranceClaimServiceReference.IInsuranceClaimService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InsuranceClaimServiceClient
        Inherits System.ServiceModel.ClientBase(Of InsuranceClaimServiceReference.IInsuranceClaimService)
        Implements InsuranceClaimServiceReference.IInsuranceClaimService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetInsuranceClaim(ByVal subscriberId As String) As InsuranceClaimServiceReference.InsuranceClaim() Implements InsuranceClaimServiceReference.IInsuranceClaimService.GetInsuranceClaim
            Return MyBase.Channel.GetInsuranceClaim(subscriberId)
        End Function
        
        Public Function GetInsuranceClaimAsync(ByVal subscriberId As String) As System.Threading.Tasks.Task(Of InsuranceClaimServiceReference.InsuranceClaim()) Implements InsuranceClaimServiceReference.IInsuranceClaimService.GetInsuranceClaimAsync
            Return MyBase.Channel.GetInsuranceClaimAsync(subscriberId)
        End Function
        
        Public Function ClaimInsurance(ByVal insuranceClaims() As InsuranceClaimServiceReference.InsuranceClaim) As Boolean Implements InsuranceClaimServiceReference.IInsuranceClaimService.ClaimInsurance
            Return MyBase.Channel.ClaimInsurance(insuranceClaims)
        End Function
        
        Public Function ClaimInsuranceAsync(ByVal insuranceClaims() As InsuranceClaimServiceReference.InsuranceClaim) As System.Threading.Tasks.Task(Of Boolean) Implements InsuranceClaimServiceReference.IInsuranceClaimService.ClaimInsuranceAsync
            Return MyBase.Channel.ClaimInsuranceAsync(insuranceClaims)
        End Function
    End Class
End Namespace
